### ISSUE TITLE
NRPE Arguments

### ISSUE THREAD

**Issue by kadzu** [canonical/nrpe_exporter#12]
I don't have idea, but is it possible to send Arguments?

I have define mi check_load (nrpe server) as:
`command[check_load]=/usr/lib64/nagios/plugins/check_load -w 0.8 -c 1.1,1.0,0.9 -r`
Or in another check, I have to send the VM hostname.
`command[check_vm_name]=/usr/check/check_vm_node.sh $ARG1$`

Any solution?
Thanks.

**Comment by brian-brazil** [comment]
Passing arguments is not supported. If you want load you can use the node exporter, and to check if another host is up you can use the blackbox exporter - or any other exporter.
