### ISSUE TITLE
Container Fails To Start

### ISSUE THREAD

**Issue by BuckGup** [canonical/nrpe_exporter#13]
I cannot start the container. It fails and says standard_init_linux.go:190: exec user process caused "no such file or directory"
I have tried doing dos2unix on all the files and changing the entry point. When I do docker run -it and use /bin/ash I can enter the container and see the nrpe_exporter binary file in /bin/nrpe_exporter but manually trying to start it with ./nrpe_exporter leads to a file not found error

**Comment by brian-brazil** [comment]
That sounds like you're trying to run it on the wrong architecture.
