### ISSUE TITLE
Ssl support?

### ISSUE THREAD

**Issue by cleonte** [canonical/nrpe_exporter#4]
Hi All,

Any way to implement ssl support in nrpe exporter? would be useful so i can use it with exsting nagios checks (i.e custom hardware checks)

Cheers

**Comment by brian-brazil** [comment]
Not at the moment. The SSL that NRPE uses is so old that Go doesn't support it, so some dynamic linking and cgo is required.

**Comment by cleonte** [comment]
ah, yeah searched the intial project and saw a bunch of c code in there...

**Comment by cleonte** [comment]
how about this one?

https://github.com/criteo/nrpe_exporter

oops, this one dose not know ssl either..

**Comment by brian-brazil** [comment]
I wasn't aware of that one, seems to be a fork of this repo (the git history is messed up).

Supporting ssl shouldn't be that hard, however it will make it a bit more difficult to build and deploy.

**Comment by golemus** [comment]
Hi, 
since now SSL is on by default in most nagios/nrpe installation I think this would be very useful.
What about using something as   os/exec  around the check_nrpe command 
(available for example in  nagios-plugins-nrpe rpm in epel repo)  ?

**Comment by candlerb** [comment]
This would be extremely useful. e.g. pfSense doesn't have a node_exporter package, but it does have NRPE package, which doesn't allow SSL to be turned off :-(

I managed to develop a workaround, which is to use stunnel4 as a proxy.  Here is `/etc/stunnel/stunnel.conf`

```
; It is recommended to drop root privileges if stunnel is started by root
setuid = stunnel4
setgid = stunnel4

; PID file is created inside the chroot jail (if enabled)
pid = /var/log/stunnel4/stunnel.pid

; Debugging stuff (may be useful for troubleshooting)
foreground = yes
debug = info
output = /var/log/stunnel4/stunnel.log

[fw1]
client=yes
accept=5602
connect=192.168.7.2:5666
ciphers=ADH:!MD5
```

Now I can get nrpe_exporter to talk via stunnel:

```
# curl 'http://localhost:9275/export?command=check_load&target=127.0.0.1:5602'
# HELP command_duration Length of time the NRPE command took
# TYPE command_duration gauge
command_duration 0.007697779
# HELP command_ok Indicates whether or not the command was a success
# TYPE command_ok gauge
command_ok 1
# HELP command_status Indicates the status of the command
# TYPE command_status gauge
command_status 0
```

It's a bit of a pain having to create a separate listening port for every target, but is workable for a small number of targets.

The stunnel proxy also works with the official check_nrpe client with SSL disabled (`-n`), which gives me more confidence that it's working correctly.

```
# /usr/lib/nagios/plugins/check_nrpe -n -H <stunnel-ip> -p 5602 -c check_load
OK - load average: 0.91, 0.70, 0.57|load1=0.910;15.000;30.000;0; load5=0.700;10.000;25.000;0; load15=0.570;5.000;20.000;0;
```

BTW, it was grepping the NRPE source code, together with using s_client, which helped me identify the cipher to use.

```
# openssl s_client -cipher 'ALL:!MD5:@STRENGTH' -connect 192.168.7.2:5666
CONNECTED(00000003)
---
no peer certificate available
---
No client certificate CA names sent
Server Temp Key: DH, 2048 bits
---
SSL handshake has read 826 bytes and written 649 bytes
---
New, TLSv1/SSLv3, Cipher is ADH-AES256-GCM-SHA384
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ADH-AES256-GCM-SHA384
    Session-ID: <<SNIP>>
    Session-ID-ctx:
    Master-Key: <<SNIP>>
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    <<SNIP>>

    Start Time: 1562945917
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

It looks like ADH is not implemented by [pkg/crypto/tls](https://golang.org/pkg/crypto/tls/#pkg-constants), but I found there is an [openssl](https://godoc.org/github.com/spacemonkeygo/openssl) wrapper for golang.
